### ISSUE TITLE
Output of executed program is lost

### ISSUE THREAD

**Issue by banyula** [KelvinTegelaar/RunAsUser#11]
I am able to execute my script as the Current User without problems (from Local System), however all output created by Write-Output (stdout) or Write-Error (stderr) is lost and not passed back to the calling script. I checked that hStdOutput and hStdError are not used on the STARTUPINFO structure when invoking CreateProcessAsUserW.

Is there a hope for you to include that in the C# code?

Cheers,

**Comment by KelvinTegelaar** [comment]
The problem with this is that the returned output would not be PowerShell objects, but just text. You won't be able to get variables or gather any usable info from the output directly.

My C# game ain't strong enough to do get the output to actually be useful. Saving info to disk temporarily is the best solution I can think of if you really need the output. If you know any strong C# devvers that want to jump on this, feel free to invite them ;)

**Comment by banyula** [comment]
Kelvin,

I was able to modify the C# code in order to create pipes for StdOutput and StdError, so once the output is trapped it is passed to an object that is returned to PowerShell. That works only if Wait for the execution is requested. I also pass back, besides the PID that you were already doing, the ExitCode from the executing program, and the CurrentUser loginid (domain\userid). I had to modify the function a bit to be able to call, besides a Scriptblock, any Executable application because I convert my scripts into executables using PowerShellProTools of IronManSoftware.

If you are interested in my findings please tell me how I can send it to you.

VICTOR
