### ISSUE TITLE
Error When using Module via Datto RMM Process

### ISSUE THREAD

**Issue by thenaysayer** [KelvinTegelaar/RunAsUser#13]
I have been testing out some use of this function from my RMM platform, but am running into the following error when trying to invoke the scriptblock: 

```
Invoke-AsCurrentUser : Could not execute as currently logged on user: Exception calling "StartProcessAsCurrentUser" 
with "6" argument(s): "CreateProcessAsUser failed. (The filename or extension is too long, Win32ErrorCode 206 - 
0x000000CE)"
At C:\ProgramData\CentraStage\Packages\3df27131-dff5-46b0-80fb-47ca13b3806c#\command.ps1
+     Invoke-AsCurrentUser -ScriptBlock $ScriptBlock  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException,Invoke-AsCurrentUser
```

This function solves many issues I have and opens the door for some great automation, but I have to get over this hurdle first. 

I think the issue is stemming from the long pathlength of the Datto RMM Agent folder used in the $pwshPath variable when invoking the scriptblock. 

Thanks

**Comment by KelvinTegelaar** [comment]
I've seen this problem more in the last days, I'm expecting it does not have to do with the path but the length of the encoded string. It's under research and hopefully will have a fix for v2.0 soon. :)

**Comment by KelvinTegelaar** [comment]
And found the issue, this occurs when the encoded command is larger than 8000 characters. 

I'm adding logic that would allow you to save the script that runs to a temporary file instead, of course this would have to be handled with care... :)

**Comment by KelvinTegelaar** [comment]
So it's several limits really, Windows XP and 7 have a limit of 8190 characters, Windows 8.1 and up has a limit of 32767. I'll be processing this in the module.

**Comment by thenaysayer** [comment]
You rock. I look forward to the update. Let me know if you need any other info gathered related to this issue.

**Comment by KelvinTegelaar** [comment]
Changelog:
Fixed race issue where wait would never exit.
Allow expansion of strings within the scriptblock.
Fix for issue with scripts that are too long, and adding the new -CacheToDisk option.
