### ISSUE TITLE
Force scriptblock to run with Microsoft PowerShell (pwsh.exe)

### ISSUE THREAD

**Issue by vollbrechteric** [KelvinTegelaar/RunAsUser#15]
Similar to what -UseWindowsPowershell switch is doing but instead use Microsoft PowerShell (pwsh.exe).
Useful to use new features that have been added to cmdlets in RMM that uses an older version of PowerShell.
Would also need to check if pwsh is installed.

**Comment by KelvinTegelaar** [comment]
Merged PR that resolves this. Will be updating PsGallery shortly.
