### ISSUE TITLE
"Hello World" text file not created

### ISSUE THREAD

**Issue by New-Hope-Mills** [KelvinTegelaar/RunAsUser#21]
When I run the command:

`$scriptblock = { "Hello world" | out-file "C:\Temp\HelloWorld.txt" }    
invoke-ascurrentuser -scriptblock $scriptblock`

All it returns is a number, which I assume is the PID. However it does not actually create a txt file. 
I can, however, add the file with `"Hello World" | Out-File "C:\Temp\HelloWorld.txt"`

I'm executing as SYSTEM, using ConnectWise Control, with backstage Admin PowerShell, if that helps.

**Comment by jeremyroe** [comment]
Likely your C:\Temp does not exist - try creating that folder first or do something like the following:
New-Item -ItemType Directory -Force -Path C:\Temp\
Check if first with Test-Path if you want

**Comment by KelvinTegelaar** [comment]
correct @jeremyroe, thanks for answers. :)

@new-hope-mills FYI Backstage and RunAsUser do not work together. Backstage is an interactive user session so RunAsUser grabs that.
