### ISSUE TITLE
Could not execute as currently logged on user

### ISSUE THREAD

**Issue by clifford64** [KelvinTegelaar/RunAsUser#23]
I am getting this error and not sure what is going on. Using Workspace One to deploy the script and according to task manager, it is running as SYSTEM.

```
Invoke-AsCurrentUser : Could not execute as currently logged on user: Exception calling "StartProcessAsCurrentUser" 
with "6" argument(s): "CreateProcessAsUser failed. (Access is denied, Win32ErrorCode 5 - 0x00000005)"
At C:\ProgramData\AirWatchMDM\AppDeploymentCache\{4183D963-3ED9-414C-B291-DDF79F0B9DAF}\testnotify.ps1:44 char:1
+ Invoke-AsCurrentUser -scriptblock $scriptblock -UseWindowsPowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException,Invoke-AsCurrentUser

```
Any ideas? I have tried with -UseWindowsPowerShell, -NonElevatedSession, and setting the scriptblock before the invoke command.

**Comment by adstep** [comment]
Also hitting the same issue. Anyone have ideas?

**Comment by clifford64** [comment]
> Also hitting the same issue. Anyone have ideas?

With workspace one. I believe I was able to get it working by changing the parameters in workspace one to run as a user installation instead of admin. It still ran the install with admin privileges, but it exposed more of the install to the user allowing the script to work.

**Comment by adstep** [comment]
What's a workspace one? I can't find any mention to workspaces in the code.

**Comment by jeremyroe** [comment]
Identical issue occurring here.  We've been using the module to send notifications to the user in a migration project.  Suddenly the other day we ran into this error.  We've now seen it on 3 systems.  Initially I thought Intune Baseline security was blocking impersonation, but I've duplicated the issue on non-enrolled machines and non-organization systems.

I'm now able to trigger the issue simply by running the "hello world" code in a System Powershell window directly on a box to test for the problem.  I can see the Logon and Special logon impersonation logs appear in the event viewer, but no failures.  Also no clear indication of what could be triggering the problem.  

Has there been a new windows update causing issues?  Has anyone encountered any AV, security products, or policies that block this from working?

`invoke-ascurrentuser : Could not execute as currently logged on user: Exception calling "StartProcessAsCurrentUser"
with "6" argument(s): "CreateProcessAsUser failed. (Access is denied, Win32ErrorCode 5 - 0x00000005)"
At line:1 char:1
+ invoke-ascurrentuser -scriptblock $scriptblock
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException,Invoke-AsCurrentUser`

**Comment by mdouek** [comment]
@clifford64 @jeremyroe  I'm encountering the same issue. Did you ever find a solution?
