### ISSUE TITLE
Elevated token on user after sign in

### ISSUE THREAD

**Issue by fintechestenberg** [KelvinTegelaar/RunAsUser#24]
I have the following use case;

User is not local admin.
I have schedueled task that is running as system the task does the following;

1. add the user to the administrators group
2. Run invoke-ascurrentuser with winget upgrade --all to update all installed applications, where some of them does require admin elevation
3. remove user from administrators group

WHat happens is that in step 2, the user is not elevated even though it has admingroupmembership and application updates fails.

I'm guessing the current users token is not refreshed or something like that, is there something that can be done here? any tips welcome

**Comment by sunjiayu256** [comment]
It will be nice to see a new switch for elevating a non-local admin user with admin privileges directly while calling the command invoke-ascurrentuser.

**Comment by KelvinTegelaar** [comment]
Add a klist purge to remove all tickets and refresh the tokens for the user to perform this. The system is using cached groups/tokens and thus never sees that the user is now local admin.
