### ISSUE TITLE
Module Manifest/Nuspec Version Mismatch

### ISSUE THREAD

**Issue by jyonke** [KelvinTegelaar/RunAsUser#26]
**Describe the bug**
Installing RunAsUser outside of the PSGallery results in an invalid module being installed

**To Reproduce**

Download the raw nupkg from the PSGallery.
Upload to internal hosted repository (ex: Sonatype Nexus - Nuget v2).
Register internal PowerShell repository .
Install RunAsUser Module from internal repository.
Import Module

**Expected behavior**
The Module imports with the proper version and is recognized as a valid PowerShell Module

**Software (please complete the following information):**

OS: Microsoft Windows 10 20H2 19042.1237
PowerShell Version: 5.1.19041. 1237
PowerShellGet Module: 1.0.0.1

**Additional context**
This seems to be a result of the NuGet standards adhering to semantic versioning requiring a Major.Minor.Patch scheme . The result is the wrong path being created when installing the module and then when importing the path and module manifest versions are not matched. If the Module Manifest is modified to version 2.2.0 or the path is updated to 2.2 the module imports as expected. A potential fix would be to update the module manifest version to major.minor.patch to be compliant.

https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#normalized-version-numbers
https://github.com/NuGet/Home/issues/3050

**Screenshots**
![Screenshot 2021-12-05 215236](https://user-images.githubusercontent.com/19600775/144780072-22bc14fd-b2cd-4654-bbe7-5610016e7171.png)
![Screenshot 2021-12-05 215836](https://user-images.githubusercontent.com/19600775/144780104-585824f4-cdc0-4947-a19b-4e291a9198de.png)

**Comment by KelvinTegelaar** [comment]
Fixed :)
