### ISSUE TITLE
Add switch to run impersonated with admin permissions?

### ISSUE THREAD

**Issue by o-l-a-v** [KelvinTegelaar/RunAsUser#3]
This module would be of great help in scenarios where you have to install packages from Intune MDM that requires admin permissions but that can't run as NT AUTHORITY\SYSTEM.

Currently, RunAsUser seems to run without admin permissions. Is this something that can be added with a optional boolean?

I tested with following code, running as SYSTEM.

```powershell
# Test command
Invoke-AsCurrentUser -ScriptBlock {
    # Assets
    $FilePath = [string]('{0}\whoami-{1}.txt' -f ([System.Environment]::GetFolderPath('Desktop'),[datetime]::Now.ToString('yyyyMMdd-HHmmss')))
    $OutText  = [string]('UPN:   {0}{1}' -f ((whoami /upn),[System.Environment]::NewLine))
    $OutText += [string]('UN:    {0}{1}' -f ((whoami),[System.Environment]::NewLine))
    $OutText += [string]('Admin: {0}{1}' -f (
        [string]([System.Security.Principal.WindowsPrincipal][System.Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator),
        [System.Environment]::NewLine
    ))
    
    # Output file
    $null = Out-File -FilePath $FilePath -Encoding 'utf8' -InputObject $OutText
}
```

**Comment by KelvinTegelaar** [comment]
Seems possible and like a good plan. Marked as enhancement and will see about adding soon. Thanks! :)

**Comment by KelvinTegelaar** [comment]
Implemented in a local test version but seems to behave erratic. Works when UAC is completely disabled, otherwise it works 30% of the time. Still in research :)

**Comment by KelvinTegelaar** [comment]
Can't get it to work consistently. I think I'd need a C# and UAC expert for this. Adding the 'help required' tag. :)
