### ISSUE TITLE
Add optional parameter to run as SID, even though user is not logged in?

### ISSUE THREAD

**Issue by o-l-a-v** [KelvinTegelaar/RunAsUser#4]
When running scripts or installers from Intune MDM as system, these can be run even though no user is actually logged in. In these scenarios, impersonating with RunAsUser would probably fail.

Would it be possible to add a optional inpit parameter where one could specify a SID to run as, even though the user is not logged in? I'm thinking silent installs of MSI and EXE installers in particular.

**Comment by KelvinTegelaar** [comment]
The .NET/C# CreateProcessAsUser requires tokens of a user that already has an interactive session. (https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasusera). 

I am not able to add this myself as it would involve generating a token for a user, which would require this users credentials. For now I'll have to consider this an issue I can't pick up. Sorry. :(

**Comment by jborean93** [comment]
Technically this is possible to do but it's pretty complex code. You can call `[LsaLogonUser](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-lsalogonuser) with a [KERB_S4U_LOGON](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/ns-ntsecapi-kerb_s4u_logon) auth info structure. This allows you to create a new access token for both a local and domain account without knowing their password.

In saying that calling `LsaLogonUser` is not an easy task at all.
