### ISSUE TITLE
Return the process ID of the new process to aid in waiting

### ISSUE THREAD

**Issue by tabs-not-spaces** [KelvinTegelaar/RunAsUser#5]
might require some tinkering with the assembly type code, but should be possible to identify the process details of the process that is generated so we could return it back with a <code>-PassThru</code> or  <code>-Wait</code> parameter.

Use case is obviously there..

``` PowerShell
"do the things.."
$proc = Invoke-AsCurrentUser -ScriptBlock { (1..1000) | % { $_ } } -PassThru
While ( Get-Process $prod.Id) {
    Start-Sleep -Milliseconds 100
}
"do the next things..."
```

I'm happy to take a crack at it, but figured I'd put it up here incase others could do it faster.

**Comment by KelvinTegelaar** [comment]
Maybe the opposite is a better though - Always wait until -Nowait is declared, as in most cases you want to do something with the output I think.

Opinion?

**Comment by KelvinTegelaar** [comment]
I'd solve the waiting within the C# code though. I'll upload an example to a beta branch for demonstration purposes.

**Comment by KelvinTegelaar** [comment]
Added the nowait in latest beta commit. Would love to hear your thoughts.

**Comment by KelvinTegelaar** [comment]
Pretty sure this is tackled in the latest version, we're waiting by default, if -nowait is specified it'll return the pid to make your own waiting logic.
