### ISSUE TITLE
Ability to pass variables in scriptblock

### ISSUE THREAD

**Issue by Negwoh** [KelvinTegelaar/RunAsUser#7]
I was looking for a way to pass script or global scope variables to the spawned process and came up with the below example:
```
$test = "hello world!"
$ScriptBlockText = "Toast -Text `"$test`""
 
$ScriptBlock = [Scriptblock]::Create($ScriptBlockText)
 
Invoke-AsCurrentUser -ScriptBlock $ScriptBlock
```
![image](https://user-images.githubusercontent.com/13195181/89147817-f1bc6100-d5ab-11ea-951c-7f4c8af25b01.png)
Which gives my what I need but means I have to form a string to get the variables to expand before they are encoded.

Ideally, we could have the same functionality as Invoke-Command utilizing a -ArugementList or better yet, using the $Using: scope (wishful thinking here I think).

**Comment by KelvinTegelaar** [comment]
I think you'll be better of storing the variables inside of the scriptblock itself as such:

$Scriptblock = {
$var = "hello world"
toast -text $var
}

$Using:Scope would not work as we're creating an entirely new PowerShell process. Could you eleborate a little on the -argumenlist example a little more so I'm sure we're talking about the same thing? :)

**Comment by Negwoh** [comment]
The problem with storing the variables inside the scriptblock is that they cant be re-used or passed from system.
To expand on my current scenario, I have a longish script that needs to run as System (from DRMM) and I want to keep the user updated on progress and updates and at the moment I have to copy paste the toast code every time I want to do this instead of having a function that I can call to update.
Simplified example that does not work:
```
function DoSomeComplicatedSystemStuff {
    return "Complete"
}

$PromptText = DoSomeComplicatedSystemStuff

Invoke-AsCurrentUser -ScriptBlock {
    Toast -Text $PromptText
}
```
![image](https://user-images.githubusercontent.com/13195181/89221975-4e5d6180-d628-11ea-8e16-6d5d5cbbb847.png)

To get this to work, I would need to do this:
```
function DoSomeComplicatedSystemStuff {
    return "Complete"
}

$PromptText = DoSomeComplicatedSystemStuff
$ScriptBlockText = "Toast -Text `"$PromptText`"" 
$ScriptBlock = [Scriptblock]::Create($ScriptBlockText)

Invoke-AsCurrentUser -ScriptBlock $ScriptBlock
```
![image](https://user-images.githubusercontent.com/13195181/89222060-78168880-d628-11ea-865b-232a5d78f87b.png)

Regarding the -ArgumentList, this is an object passed to Invoke-Command that contains variable data, example stolen from https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-7:
```
$parameters = @{
    ComputerName = "Server01"
    ScriptBlock = { Param ($param1,$param2) Get-ChildItem -Name $param1 -Include $param2 }
    ArgumentList = "a*", "*.pdf"
}
Invoke-Command @parameters

aa.pdf
ab.pdf
ac.pdf
az.pdf
```
A mock example of Invoke-AsCurrentUser using -ArgumentList would be:
```
function DoSomeComplicatedSystemStuff {
    return "Complete"
}

$PromptText = DoSomeComplicatedSystemStuff
$ScriptBlock = {
    Param($Param1)
    Toast -Text $Param1
}

Invoke-AsCurrentUser -ScriptBlock $ScriptBlock -ArgumentList @($PromptText)
```

**Comment by KelvinTegelaar** [comment]
Looking into this. Consider it under development. :)

**Comment by KelvinTegelaar** [comment]
Haven't had time to tackle this yet. Still in progress.. :)

**Comment by KelvinTegelaar** [comment]
Didn't get back to this for a long time as I had no time. Still in progress and not forgotten! :)

**Comment by sgexcit** [comment]
I'm running RunAsUser v2.2 and even after this commit I cannot get variables outside the ScriptBlock to pass inside of the ScriptBlock when running Invoke-AsCurrentUser. As I read it, the commit @cybermoloch provided looks like it should be evaluating these variables automatically.

**Comment by cybermoloch** [comment]
@sgexcit Can you post your code in a gist or similar so we can see it?

**Comment by KelvinTegelaar** [comment]
Reopening as I had to remove the functionality in 2.2 due to backwards compatibility issues

**Comment by KelvinTegelaar** [comment]
Hey @sgexcit and @cybermoloch,

I had to remove this option for a bit because when having variables that aren't referenced before the scriptblock would evaluate to $null. e.g.

```powershell

$Scriptblock = { $item2 = $bla.item2}
```
would be
```powershell
 = .item2
```

Fixing this by making variable expansion optional in next version. :)

**Comment by sgexcit** [comment]
Awesome @KelvinTegelaar! I appreciate you confirming that and I'll be sure to keep an eye out for that release!

**Comment by ztrhgf** [comment]
I've added support for passing arguments. Just check https://github.com/ztrhgf/RunAsUser/blob/master/Public/Invoke-AsCurrentUser.ps1

**Comment by CBOTY** [comment]
@KelvinTegelaar - With this being removed from v2.2 is there any timeline on re-introduction or a workaround to pass parameters through.
