### ISSUE TITLE
Could not execute as currently logged on user

### ISSUE THREAD

**Issue by Tom-FT** [KelvinTegelaar/RunAsUser#8]
we are getting this error when using Invoke-AsCurrentUser, but not all the time and not on all computers.

we are using it to send an email as the local user, so we are creating a script block to trigger a new email from outlook with certain things pre-filled in, the new email pops up, the user then fills in the rest of the info and then clicks send.

it seems to run ok once for most users but then if they try to run it again it doesn't always work, the error we are getting is

Invoke-AsCurrentUser : Could not execute as currently logged on user: Exception calling "StartProcessAsCurrentUser" with "6" argument(s): "WTSQueryUserToken failed to get access token. (A required privilege is not held by
the client, Win32ErrorCode 1314 - 0x00000522)"
At C:\Users\*****\EmailFTSupport - Screenshot.ps1:79 char:1
+ Invoke-AsCurrentUser -ScriptBlock $scriptblock
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException,Invoke-AsCurrentUser

I feel we are either missing something simple or there is something that's not quite right. it is saying that a privilege is not held on the client but we are not sure what privilege this is referring to.

Cheers

Tom

**Comment by KelvinTegelaar** [comment]
Are you running an EDR solution by chance? I've seen RunAsUser fail to get a token when an EDR application blocks it. You might have to think about whitelisting if you are.

Could you also try with the -NonElevatedSession switch? thanks for helping me troubleshoot.

**Comment by Tom-FT** [comment]
Hi, sorry thought I would get a notification when you replied but didn't see it.

not sure what you mean by an EDR Solution, we are using Datto RMM if that's what you mean. we think we have got round it for the moment by installing the module everytime the script is run but I'll also try the nonelevatedsession switch as well just in case that is a better solution.

Cheers

Tom

**Comment by jborean93** [comment]
[WTSQueryUserToken](https://docs.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsqueryusertoken) is a pretty highly privileged function and requires the caller to be running the the `SYSTEM` account and with the `SeTcbPrivilege` privilege.

> To call this function successfully, the calling application must be running within the context of the LocalSystem account and have the SE_TCB_NAME privilege.

How are you running this function?

**Comment by Tom-FT** [comment]
Hi, we have now deployed the script with the -NonElevatedSession switch and this seems to have resolved the problem. we will continue to monitor it and get back to you if we are still having problems

**Comment by KelvinTegelaar** [comment]
Closed :) Thanks.
